version: '3'

services:
  siproad-db:
    image: mariadb:10.11
    container_name: ${DOCKER_DB_CONTAINER_NAME}
    restart: always
    environment:
      MYSQL_DATABASE: ${ADMIN_DB_NAME}
      MYSQL_USER: ${ADMIN_DB_USERNAME}
      MYSQL_PASSWORD: ${ADMIN_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "${DOCKER_DB_PORT}:3306"
    volumes:
      - ./${DOCKER_DB_VOLUMEN}:/var/lib/mysql
  siproad-api:
    depends_on:
      - siproad-db
    build: 
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_IMG_NAME}
    container_name: ${DOCKER_APP_CONTAINER_NAME}
    restart: always
    ports:
      - "${PORT}:${PORT}"
    # working_dir: /var/www/pokedex
    environment:
      PORT: ${PORT}
      HTTP_TIMEOUT: ${HTTP_TIMEOUT}
      HTTP_MAX_REDIRECTS: ${HTTP_MAX_REDIRECTS}
      EXECUTION_RETRIES: ${EXECUTION_RETRIES}
      EXECUTION_BASE_DELAY: ${EXECUTION_BASE_DELAY}
      ADMIN_DB_HOST: ${ADMIN_DB_HOST}
      ADMIN_DB_PORT: ${ADMIN_DB_PORT}
      ADMIN_DB_NAME: ${ADMIN_DB_NAME}
      ADMIN_DB_USERNAME: ${ADMIN_DB_USERNAME}
      ADMIN_DB_PASSWORD: ${ADMIN_DB_PASSWORD}
      PRODUCTS_DB_HOST: ${PRODUCTS_DB_HOST}
      PRODUCTS_DB_PORT: ${PRODUCTS_DB_PORT}
      PRODUCTS_DB_NAME: ${PRODUCTS_DB_NAME}
      PRODUCTS_DB_USERNAME: ${PRODUCTS_DB_USERNAME}
      PRODUCTS_DB_PASSWORD: ${PRODUCTS_DB_PASSWORD}
      DB_DEFAULT_LIMIT: 1000
    # volumes:
    #   - ./:/var/www/pokedex